apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesJson6902:
  - target:
      kind: Namespace
      version: v1
      name: linkerd-bench
    path: inject_linkerd.yml
