---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: server
  namespace: linkerd-bench
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: linkerd-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      serviceAccountName: server
      containers:
        - name: fortio
          image: fortio/fortio:latest
          args: ["server"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8079
              name: grpc
          resources:
            limits:
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: linkerd-bench
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 8888
      targetPort: 8888
    - name: grpc
      port: 7777
      targetPort: 7777
